namespace ChromeProtocol.Tools.CodeGeneration.Emitting;

public class CsharpFile : IEmittable
{
  public ICollection<string> Usings { get; set; } = new LinkedList<string>();

  public ICollection<CsharpNamespaceDecl> Namespaces { get; set; } = new LinkedList<CsharpNamespaceDecl>();

  public void Emit(SourceCodeEmitter emitter, EmissionState state)
  {
    emitter.EmitLineIdented("// <auto-generated />", ref state);
    emitter.EmitLineIdented("#nullable enable", ref state);

    foreach (var nameSpace in Usings)
    {
      emitter.EmitLineIdented($"using {nameSpace};", ref state);
    }

    emitter.EmitEmptyLine(ref state);

    foreach (var namespaceDecl in Namespaces)
    {
      namespaceDecl.Emit(emitter, state);
    }
  }
}
