// <auto-generated />
#nullable enable

namespace Protocol.Generated
{
  public static partial class DotnetRuntime
  {
    /// <summary>
    /// An alias for different version of Runtime.callFunctionOn used in Mono proxy.<br/>
    /// Don&#39;t use directly, send it as Runtime.callFunctionOn command.<br/>
    /// </summary>
    /// <param name="ObjectId">TBD</param>
    /// <param name="TypeName">TBD</param>
    /// <param name="MethodName">TBD</param>
    public static Protocol.Generated.DotnetRuntime.CallFunctionOnRequest CallFunctionOn(string ObjectId, string TypeName, string MethodName)    
    {
      return new Protocol.Generated.DotnetRuntime.CallFunctionOnRequest(ObjectId, TypeName, MethodName);
    }
    /// <summary>
    /// An alias for different version of Runtime.callFunctionOn used in Mono proxy.<br/>
    /// Don&#39;t use directly, send it as Runtime.callFunctionOn command.<br/>
    /// </summary>
    /// <param name="ObjectId">TBD</param>
    /// <param name="TypeName">TBD</param>
    /// <param name="MethodName">TBD</param>
    [JetBrains.Wasm.Debugger.ChromeProtocol.Core.MethodName("DotnetRuntime.callFunctionOn")]
    public record CallFunctionOnRequest(
      [property: Newtonsoft.Json.JsonProperty("objectId")]
      string ObjectId,
      [property: Newtonsoft.Json.JsonProperty("typeName")]
      string TypeName,
      [property: Newtonsoft.Json.JsonProperty("methodName")]
      string MethodName
    ) : JetBrains.Wasm.Debugger.ChromeProtocol.Core.ICommand<CallFunctionOnRequestResult>
    {
    }
    /// <param name="Result">TBD</param>
    public record CallFunctionOnRequestResult(
      [property: Newtonsoft.Json.JsonProperty("result")]
      Newtonsoft.Json.Linq.JObject Result
    ) : JetBrains.Wasm.Debugger.ChromeProtocol.Core.IType
    {
    }
  }
}
