// <auto-generated />
#nullable enable

namespace Protocol.Generated
{
  /// <summary>TBD</summary>
  public static partial class DotnetDebugger
  {
    /// <summary>TBD.</summary>
    /// <param name="ScriptId">Script identifier as reported in the `Debugger.scriptParsed`.</param>
    /// <param name="LineNumber">Line number in the script (0-based).</param>
    /// <param name="ColumnNumber">Column number in the script (0-based).</param>
    public record SourceLocationType(
      [property: Newtonsoft.Json.JsonProperty("scriptId")]
      Protocol.Generated.Runtime.ScriptIdType ScriptId,
      [property: Newtonsoft.Json.JsonProperty("lineNumber")]
      int LineNumber,
      [property: Newtonsoft.Json.JsonProperty("columnNumber")]
      int? ColumnNumber = default
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>TBD.</summary>
    /// <param name="JustMyCodeStepping">If true, enables stepping only into user code, not library one.</param>
    public static Protocol.Generated.DotnetDebugger.SetDebuggerPropertyRequest SetDebuggerProperty(bool JustMyCodeStepping)
    {
      return new Protocol.Generated.DotnetDebugger.SetDebuggerPropertyRequest(JustMyCodeStepping);
    }
    /// <summary>TBD.</summary>
    /// <param name="JustMyCodeStepping">If true, enables stepping only into user code, not library one.</param>
    [ChromeProtocol.Core.MethodName("DotnetDebugger.setDebuggerProperty")]
    public record SetDebuggerPropertyRequest(
      [property: Newtonsoft.Json.JsonProperty("JustMyCodeStepping")]
      bool JustMyCodeStepping
    ) : ChromeProtocol.Core.ICommand<SetDebuggerPropertyRequestResult>
    {
    }
    /// <param name="JustMyCodeEnabled">TBD</param>
    public record SetDebuggerPropertyRequestResult(
      [property: Newtonsoft.Json.JsonProperty("justMyCodeEnabled")]
      bool? JustMyCodeEnabled = default
    ) : ChromeProtocol.Core.IType
    {
    }
    /// <summary>TBD</summary>
    /// <param name="Location">TBD</param>
    public static Protocol.Generated.DotnetDebugger.SetNextIPRequest SetNextIP(Protocol.Generated.DotnetDebugger.SourceLocationType Location)
    {
      return new Protocol.Generated.DotnetDebugger.SetNextIPRequest(Location);
    }
    /// <summary>TBD</summary>
    /// <param name="Location">TBD</param>
    [ChromeProtocol.Core.MethodName("DotnetDebugger.setNextIP")]
    public record SetNextIPRequest(
      [property: Newtonsoft.Json.JsonProperty("location")]
      Protocol.Generated.DotnetDebugger.SourceLocationType Location
    ) : ChromeProtocol.Core.ICommand<SetNextIPRequestResult>
    {
    }
    public record SetNextIPRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>TBD</summary>
    /// <param name="ModuleGUID">TBD</param>
    /// <param name="Dmeta">The metadata changes to be applied</param>
    /// <param name="Dil">The IL changes to be applied</param>
    /// <param name="Dpdb">The PDB changes to be applied</param>
    public static Protocol.Generated.DotnetDebugger.ApplyUpdatesRequest ApplyUpdates(string ModuleGUID, string Dmeta, string Dil, string Dpdb)
    {
      return new Protocol.Generated.DotnetDebugger.ApplyUpdatesRequest(ModuleGUID, Dmeta, Dil, Dpdb);
    }
    /// <summary>TBD</summary>
    /// <param name="ModuleGUID">TBD</param>
    /// <param name="Dmeta">The metadata changes to be applied</param>
    /// <param name="Dil">The IL changes to be applied</param>
    /// <param name="Dpdb">The PDB changes to be applied</param>
    [ChromeProtocol.Core.MethodName("DotnetDebugger.applyUpdates")]
    public record ApplyUpdatesRequest(
      [property: Newtonsoft.Json.JsonProperty("moduleGUID")]
      string ModuleGUID,
      [property: Newtonsoft.Json.JsonProperty("dmeta")]
      string Dmeta,
      [property: Newtonsoft.Json.JsonProperty("dil")]
      string Dil,
      [property: Newtonsoft.Json.JsonProperty("dpdb")]
      string Dpdb
    ) : ChromeProtocol.Core.ICommand<ApplyUpdatesRequestResult>
    {
    }
    public record ApplyUpdatesRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>Note: this command will never respond, so don&#39;t wait for the response. When succeeded, it will emit &#39;Debugger.scriptParsed&#39; event per each parsed .NET source file.</summary>
    /// <param name="Url">TBD</param>
    public static Protocol.Generated.DotnetDebugger.AddSymbolServerUrlRequest AddSymbolServerUrl(string Url)
    {
      return new Protocol.Generated.DotnetDebugger.AddSymbolServerUrlRequest(Url);
    }
    /// <summary>Note: this command will never respond, so don&#39;t wait for the response. When succeeded, it will emit &#39;Debugger.scriptParsed&#39; event per each parsed .NET source file.</summary>
    /// <param name="Url">TBD</param>
    [ChromeProtocol.Core.MethodName("DotnetDebugger.addSymbolServerUrl")]
    public record AddSymbolServerUrlRequest(
      [property: Newtonsoft.Json.JsonProperty("url")]
      string Url
    ) : ChromeProtocol.Core.ICommand<AddSymbolServerUrlRequestResult>
    {
    }
    public record AddSymbolServerUrlRequestResult() : ChromeProtocol.Core.IType
    {
    }
    /// <summary>TBD</summary>
    /// <param name="AssemblyName">TBD</param>
    /// <param name="TypeName">TBD</param>
    /// <param name="MethodName">TBD</param>
    public static Protocol.Generated.DotnetDebugger.GetMethodLocationRequest GetMethodLocation(string AssemblyName, string TypeName, string MethodName)
    {
      return new Protocol.Generated.DotnetDebugger.GetMethodLocationRequest(AssemblyName, TypeName, MethodName);
    }
    /// <summary>TBD</summary>
    /// <param name="AssemblyName">TBD</param>
    /// <param name="TypeName">TBD</param>
    /// <param name="MethodName">TBD</param>
    [ChromeProtocol.Core.MethodName("DotnetDebugger.getMethodLocation")]
    public record GetMethodLocationRequest(
      [property: Newtonsoft.Json.JsonProperty("assemblyName")]
      string AssemblyName,
      [property: Newtonsoft.Json.JsonProperty("typeName")]
      string TypeName,
      [property: Newtonsoft.Json.JsonProperty("methodName")]
      string MethodName
    ) : ChromeProtocol.Core.ICommand<GetMethodLocationRequestResult>
    {
    }
    /// <param name="Line">TBD</param>
    /// <param name="Column">TBD</param>
    /// <param name="Url">TBD</param>
    public record GetMethodLocationRequestResult(
      [property: Newtonsoft.Json.JsonProperty("line")]
      int Line,
      [property: Newtonsoft.Json.JsonProperty("column")]
      int Column,
      [property: Newtonsoft.Json.JsonProperty("url")]
      string Url
    ) : ChromeProtocol.Core.IType
    {
    }
  }
}
