// <auto-generated />
#nullable enable

namespace Protocol.Generated
{
  /// <summary>Contains commands and events related to Mono runtime.</summary>
  public static partial class Mono
  {
    /// <summary>Issued when Mono runtime is ready to use.</summary>
    [ChromeProtocol.Core.MethodName("Mono.runtimeReady")]
    public record RuntimeReady() : ChromeProtocol.Core.IEvent
    {
    }
  }
}
