name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: src

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64]
        include:
          - os: macos-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: 📝 Fetch Sources
        uses: actions/checkout@v6

      - name: 🛠 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: 🏗 Restore dependencies
        run: dotnet restore

      - name: 🏗 Build
        run: dotnet build --no-restore

      - name: 📝 Test ChromeProtocol.Core
        run: dotnet test --no-build --verbosity normal ChromeProtocol.Core.Tests

      - name: 📝 Test ChromeProtocol.Runtime
        run: dotnet test --no-build --verbosity normal ChromeProtocol.Runtime.Tests

      - name: 📝 Test ChromeProtocol.Tools
        run: dotnet test --no-build --verbosity normal --logger "console;verbosity=detailed" ChromeProtocol.Tools.Tests